# Generated by Django 4.0.6 on 2022-08-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='cit',
            new_name='city',
        ),
    ]
